-- No output
SET PAGES 0
SET FEEDBACK OFF
SET TERM OFF
SET TIMING OFF
SET PAUSE OFF
SET TRIMSPOOL ON
SET HEAD OFF
SET FEED OFF
SET ECHO OFF

-- Exit on error
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- Set edition for admin to base
ALTER DATABASE DEFAULT EDITION = ORA$BASE;
ALTER SESSION SET EDITION = ORA$BASE;

-- Create base edition
DECLARE 
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO l_exists
    FROM DBA_EDITIONS
    WHERE EDITION_NAME='EDITION_MAIN';
    IF l_exists=0 THEN
        EXECUTE IMMEDIATE 'CREATE EDITION EDITION_MAIN AS CHILD OF ORA$BASE';
    END IF;
END;
/

GRANT USE ON EDITION EDITION_MAIN TO PUBLIC;
ALTER DATABASE DEFAULT EDITION = EDITION_MAIN;
ALTER SESSION SET EDITION = EDITION_MAIN;